id: P009188
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 19:27:11.654136
source_metadata:
  id: bdr:W1KG1687
  title: བོད་ཀྱི་བན་སེར་མོ་བ་
  author: ''
  volumes:
    be198269f8594df2bee6128c3e47827d:
      image_group_id: I1KG1836
      title: ''
      volume_number: 1
      total_pages: 220
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
